config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }
  root to: "pages#home"
  get "home", to: 'pages#home'
  get "specialties", to: 'pages#specialties'
  get "services", to: 'pages#services'
  get "price", to: 'pages#price'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/doctor.rb
class Doctor < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include DeviseWhitelist
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
    extend ActiveSupport::Concern

    included do
        before_action :configure_permitted_parameters, if: :devise_controller?
    end

    private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def specialties
  end

  def services
  end

  def price
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evaluacion</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= render 'shared/navbar' %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>


      <%= yield %>
      

    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/price.html.erb
<h1>Pages#price</h1>
<p>Find me in app/views/pages/price.html.erb</p>

app/views/pages/services.html.erb
<h1>Pages#services</h1>
<p>Find me in app/views/pages/services.html.erb</p>

app/views/pages/specialties.html.erb
<h1>Pages#specialties</h1>
<p>Find me in app/views/pages/specialties.html.erb</p>

app/views/shared/_navbar.html.erb
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'Inicio', home_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'Especialidades', specialties_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'Servicios', services_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'Costos', price_path, class:"nav-link"%>
            </li>
            

               <% if current_user %>
               <%= link_to "Cerrar sesión", destroy_user_session_path, data: { turbo_method: :delete }, class:"nav-link" %>
               <% else %>
               <%= link_to "Registrarse", new_user_registration_path, class:"nav-link" %>
               <%= link_to "Iniciar sesión", new_user_session_path, class:"nav-link" %>
               <% end %>



          </ul>

        </div>

      </div>
    </nav>